# Generated by Django 3.2.23 on 2023-11-09 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('usertype', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='request_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('payment_status', models.CharField(max_length=100)),
                ('payment_date', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrption', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='service_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('latitude', models.CharField(max_length=100)),
                ('longitude', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='service_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('place', models.CharField(max_length=100)),
                ('post', models.CharField(max_length=100)),
                ('pin', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('photo', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.login')),
            ],
        ),
        migrations.CreateModel(
            name='subcatogary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcatogary_name', models.CharField(max_length=100)),
                ('SERVICE_TYPE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service_provider')),
            ],
        ),
        migrations.CreateModel(
            name='service_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.CharField(max_length=100)),
                ('SERVICE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='service',
            name='SERVICE_PROVIDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service_provider'),
        ),
        migrations.AddField(
            model_name='service',
            name='SUBCATEGORY',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.subcatogary'),
        ),
        migrations.CreateModel(
            name='request_sub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_date', models.CharField(max_length=100)),
                ('REQUEST', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.request_service')),
                ('SERVICE', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service')),
            ],
        ),
        migrations.AddField(
            model_name='request_service',
            name='SERVICE_PROVIDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service_provider'),
        ),
        migrations.AddField(
            model_name='request_service',
            name='USER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.user'),
        ),
        migrations.CreateModel(
            name='rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('SERVICE_PROVIDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('reply', models.CharField(max_length=100)),
                ('reply_date', models.CharField(max_length=100)),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('SERVICE_PROVIDER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service_provider')),
                ('USER', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.user')),
            ],
        ),
        migrations.CreateModel(
            name='bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100)),
                ('IFSC_code', models.CharField(max_length=100)),
                ('account_no', models.CharField(max_length=100)),
                ('amount', models.CharField(max_length=100)),
                ('LOGIN', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.login')),
            ],
        ),
    ]
