# Generated by Django 3.2.23 on 2023-12-09 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maries_app', '0002_alter_subcatogary_service_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='SERVICE_PROVIDER',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='maries_app.service_provider'),
        ),
    ]
